#! /usr/bin/env python

"""Timing Constants"""
# Time each tick takes, in seconds
TICK_TIME = .01
# Maximum amount of ticks for the game to run for
# Currently set to 10 minutes
MAX_RUNTIME = 10 * 60 * 100

"""TOWERS"""
BASE_TOWER_DAMAGE = 1
# Maximum upgrade level for towers and units
MAX_UPGRADE = 3
TOWER_SELL_SCALAR = 1
TOWER_BASE_COST = 1
TOWER_RANGE = {0:1, 1:1, 2:2, 3:2}
TOWER_UPGRADE_MULTIPLIER = {0:1, 1:1.5, 2:2, 3:2.5}
TOWER_UPGRADE_COST = {0:1, 1:2, 2:3, 3:4}
TOWER_SPECIALIZE_COST = {1:3, 2:3, 3:3}

"""UNITS"""
UNIT_BASE_COST = 2
BASE_UNIT_HEALTH = 4
BASE_UNIT_DAMAGE = 1
UNIT_UPGRADE_MULTIPLIER = {0:1, 1:2, 2:3, 3:4}
UNIT_UPGRADE_COST = {0:1, 1:2, 2:3, 3:4}

"""tower/unit specialisation output damage multiplier"""
SUPER_EFFECTIVE = 1.50
EFFECTIVE = 1.1
NORMAL = 1
NOT_EFFECTIVE = 0.5

# specialisation_table[attack][defense]
SPECIALISATION_TABLE = \
  [[NOT_EFFECTIVE,   EFFECTIVE, SUPER_EFFECTIVE],
   [NORMAL,          NORMAL,    NORMAL],
   [SUPER_EFFECTIVE, EFFECTIVE, NOT_EFFECTIVE]]
def specialisation_mulitplier(attack, defense):
	return SPECIALISATION_TABLE[attack+1][defense+1]

"""PLAYER"""
BASE_RESOURCES = 5
UPGRADE_INCREASE = 8
BASE_HEALTH = 100

"""BOARD"""
#Must always be odd
BOARD_SIDE = 11
BASE_SIZE = 3
NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3
DIRECTIONS = [NORTH, EAST, SOUTH, WEST]

"""MODEL"""
SUPPLY_TIME = 15;

CONSTANTS_DICT = {
	"TICK_TIME": TICK_TIME,
	"MAX_RUNTIME": MAX_RUNTIME,
	"BASE_TOWER_DAMAGE": BASE_TOWER_DAMAGE,
	"MAX_UPGRADE": MAX_UPGRADE,
	"TOWER_SELL_SCALAR" : TOWER_SELL_SCALAR,
	"TOWER_BASE_COST" : TOWER_BASE_COST,
	"TOWER_RANGE" : TOWER_RANGE,
	"TOWER_UPGRADE_MULTIPLIER" : TOWER_UPGRADE_MULTIPLIER,
	"TOWER_UPGRADE_COST" : TOWER_UPGRADE_COST,
	"TOWER_SPECIALIZE_COST" : TOWER_SPECIALIZE_COST,
	"MAX_UPGRADE" : MAX_UPGRADE,
	"UNIT_BASE_COST" : UNIT_BASE_COST,
	"BASE_UNIT_HEALTH" : BASE_UNIT_HEALTH,
	"BASE_UNIT_DAMAGE" : BASE_UNIT_DAMAGE,
	"UNIT_UPGRADE_MULTIPLIER" : UNIT_UPGRADE_MULTIPLIER,
	"UNIT_UPGRADE_COST" : UNIT_UPGRADE_COST,
	"SUPER_EFFECTIVE" : SUPER_EFFECTIVE,
	"EFFECTIVE" : EFFECTIVE,
	"NORMAL" : NORMAL,
	"NOT_EFFECTIVE" : NOT_EFFECTIVE,
	"BASE_RESOURCES" : BASE_RESOURCES,
	"UPGRADE_INCREASE" : UPGRADE_INCREASE,
	"BASE_HEALTH" : BASE_HEALTH,
	"BOARD_SIDE" : BOARD_SIDE,
	"BASE_SIZE" : BASE_SIZE,
	"NORTH" : NORTH,
	"EAST" : EAST,
	"SOUTH" : SOUTH,
	"WEST" : WEST
}
